web/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views 

app_name = 'auth' 

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_page, name="logout"),
    path("register/", views.register_page, name="register"),
    path("setup_face/", views.setup_face_auth, name="setup_face_auth"),
    path("verify_face/", views.verify_face, name="verify_face"),
]

web/chat/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

web/mychat/urls.py
from django.contrib import admin
from django.urls import include, path
import authentication.views

urlpatterns = [
    path('', include("chat.urls")),
    path('admin/', admin.site.urls),
    
    path('auth/', include('authentication.urls', namespace='auth')), 
]

web/chat/views.py
from django.shortcuts import render, redirect


def index(request):
    if not request.user.is_authenticated:
        return redirect("auth:login")
    context={}
    return render(request, "chat/index.html", context)


def room(request, room_name):
    if not request.user.is_authenticated:
        return redirect("auth:login")
    return render(request, "chat/room.html", {"room_name": room_name})

web/chat/templates/chat/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Chat App{% endblock %}</title>
    
    {% if debug %}
        <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% else %}
        {% compress css %}
        <link rel="stylesheet" href="{% static 'src/output.css' %}">
        {% endcompress %}
    {% endif %}
</head>

<body>
    <header class="bg-white dark:bg-gray-900 shadow-md">
        {% include "chat/navbar.html" %}
    </header>

    <main>
        {% block content %}{% endblock %}
        {% block extra_scripts %}{% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
</body>

</html>

web/chat/templates/chat/chatPage.html
{% load button_components %}

<!-- <center>
        <h1>Hello, what chat room would you like to enter, {{request.user}} ?</h1>
    </center>
    <br>
    <br> -->
<div class="max-w-xl mx-auto mt-20 bg-white dark:bg-gray-900 p-8 rounded-xl shadow-md">
    <h1 class="text-2xl font-bold mb-6 text-center text-gray-800 dark:text-white">
        Hello, {{ request.user }} 👋<br>
        Quelle salle de chat veux-tu rejoindre ?
    </h1>

    <div class="flex gap-4 items-center justify-center">
        <input id="room-name-input" type="text" placeholder="Nom de la salle"
            class="w-full border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-2 text-gray-800 dark:text-white bg-gray-50 dark:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-teal-500 transition" />
        {% styled_button "Entrer" "primary" "lg" id="room-name-submit" %}
    </div>
</div>

<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function (e) {
        if (e.keyCode === 13) { // Enter key
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function (e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = roomName + '/';
    };
</script>

web/chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block title %}Accueil Chat{% endblock %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
    <div class="p-4 mb-4 text-sm rounded-lg {% if message.tags == 'error' %}text-red-800 bg-red-50 dark:bg-gray-800 dark:text-red-400{% elif message.tags == 'success' %}text-green-800 bg-green-50 dark:bg-gray-800 dark:text-green-400{% elif message.tags == 'info' %}text-blue-800 bg-blue-50 dark:bg-gray-800 dark:text-blue-400{% else %}text-gray-800 bg-gray-50 dark:bg-gray-800 dark:text-gray-400{% endif %}" role="alert">
      <span class="font-medium">
        {% if message.tags == 'error' %}Erreur:{% elif message.tags == 'success' %}Succès:{% elif message.tags == 'info' %}Info:{% else %}Message:{% endif %}
      </span>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% include "chat/chatPage.html" %}
{% endblock %}

web/chat/templates/chat/navbar.html
{% load static %}

<nav class="bg-white border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'index' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'images/boite_discussion.png' %}" class="h-6" alt="logo conversation" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Psy-chat</span>
        </a>

        <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            {% if user.is_authenticated %}
            <button type="button"
                    class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
                    <span class="sr-only">Open user menu</span>
                    {% if user.profile_photo %}
                        <img class="w-8 h-8 rounded-full" 
                             src="{{ user.profile_photo.url }}" 
                             alt="Photo de {{ user.username }}">
                    {% else %}
                        <img class="w-8 h-8 rounded-full" 
                             src="{% static 'images/default_avatar.png' %}" 
                             alt="Avatar par défaut">
                    {% endif %}
                </button>

            <!-- Dropdown menu -->            
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow-sm dark:bg-gray-700 dark:divide-gray-600"
                id="user-dropdown">
                <div class="px-4 py-3">
                    <span class="block text-sm text-gray-900 dark:text-white">{{ user.username }}</span>
                    <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">{{ user.email }}</span>
                </div>
                <ul class="py-2" aria-labelledby="user-menu-button">
                    <li>
                        <a href="#"
                            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Profil</a>
                    </li>
                    <li>
                        <a href="{% url 'auth:logout' %}"
                            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Se déconnecter</a>
                    </li>
                </ul>
            </div>
            <button data-collapse-toggle="navbar-user" type="button"
                class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-user" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M1 1h15M1 7h15M1 13h15" />
                </svg>
            </button>
        </div>

        {% endif %}

        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
            <ul
                class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a href="{% url 'index' %}"
                        class="block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500"
                        aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{% url 'room' 'general' %}"
                        class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Salle générale</a>
                </li>
                <li>
                    <a href="#"
                        class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
                </li>
            </ul>

        </div>
    </div>
    </div>
</nav>

web/chat/templates/chat/room.html
{% extends "chat/base.html" %}
{% load button_components %}

{% block title %}Salle {{ room_name }}{% endblock %}

{% block content %}

<div
    class="flex flex-col h-[80vh] max-w-2xl mx-auto mt-10 bg-white dark:bg-gray-900 rounded-xl shadow-lg overflow-hidden">

    <!-- Titre -->
    <div class="bg-teal-700 text-white py-4 px-6 text-xl font-semibold text-center">
        👋 Bienvenue dans la salle : {{ room_name }}
    </div>


    <div id="id_chat_item_container" class="flex-1 px-4 py-4 space-y-2 overflow-y-auto bg-green-50 dark:bg-gray-900">
        <!-- Les messages seront ajoutés ici dynamiquement -->
    </div>

    <div
        class="px-4 py-4 border-t border-gray-200 dark:border-gray-700 bg-gray-100 dark:bg-gray-900 flex items-center gap-2">
        <input id="chat-message-input" type="text" placeholder="Écris ton message..."
            class="flex-1 px-4 py-2 rounded-lg bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-teal-500" />
        {% styled_button "Envoyer" "primary" "lg" id="chat-message-submit" %}
    </div>
</div>


{% endblock %}

{% block extra_scripts %}
{{ room_name|json_script:"room-name" }}

<script>
    const roomName = JSON.parse(document.getElementById('room-name').textContent);
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        const isOwnMessage = data.username === "{{ request.user.username }}";

        const bubbleWrapper = document.createElement("div");
        bubbleWrapper.className = `flex ${isOwnMessage ? 'justify-end' : 'justify-start'}`;

        const bubble = document.createElement("div");
        
        bubble.className = `
        px-4 py-2 rounded-lg max-w-[70%] break-words
        ${isOwnMessage
        ? 'bg-cyan-600 text-white rounded-br-none'
        : 'bg-green-500 text-white rounded-bl-none'}
        `;
        bubble.classList.add("transition", "duration-200", "ease-in", "transform", "hover:scale-[1.02]");

        bubble.innerHTML = `<strong>${data.username}</strong><br>${data.message}`;

        bubbleWrapper.appendChild(bubble);
        document.querySelector('#id_chat_item_container').appendChild(bubbleWrapper);

        // scroll auto
        const container = document.querySelector('#id_chat_item_container');
        container.scrollTop = container.scrollHeight;
    };


    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.key === 'Enter') {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        console.log("Sending message:", message);
        chatSocket.send(JSON.stringify({
            'message': message,
            'username': '{{ request.user.username }}'
        }));
        messageInputDom.value = '';
    };
</script>
{% endblock %}